CREATE TABLE IF NOT EXISTS usuarios (
  	id_usuario INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	nome text NOT NULL,
	email text NOT NULL,
	nickname text NOT NULL,
	senha text NOT NULL,
	foto text NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);